---
title: "Seminar Report 2"
output:
  html_document:
    df_print: paged
---

Name: Erin Gunduz

Seminar Speaker's Name: Dr. Ali Deniz Güler, Ph.D. 
Seminar Speaker's Title: "Food, time and dopamine: How rewarding snacks hijack your brain""
Seminar Speaker's Affiliation: Assistant Professor of Biology at the University of Virginia

Date: Wednesday, November 7th, 2018
Time: 1:00 - 2:00 PM 

Seminar Title: Genome Sciences Seminar Series Fall 2018 hosted by the Center for Public Health Genomics 
Seminar Contact Liaison: Clint Miller 

  *Seminar Summary*: Dr. Güler began the seminar by highlighting how the Earth's rotation on its axis creates two very distinct niches, based on time and circadian rhythms. As such, he introduced the term of photoentrainment, which is the entrainment of an individual's circadian rhythm to the pattern of light and dark in the environment. The sole conduits for photoentrainment are the innate photosensitive retinal ganglion cells (RGCs). Dopamine (DA) neurotransmission and dopainergic tones influence circadian behavior and there is a connection between DA neurons, located in the ventral tegmental area (VTA) and the suprachiasmatic nucleus (SCN). Dr. Güler also mentioned that the SCN is responsible for the circadian system. Essentially, light information from the eyes are sent to the SCN and the action of the neurons vary in activity throughout the day. For example, there is a higher rate of neuron firing during the day than the rate at night. The two major types of RGCs, rod and cone photoreceptor cells, then project neurons that are directed towards the brain, which is ultimately sent to the SCN to control the circadian rhythms. 
  
  *Overarching Research Topic*: Dr. Güler's main research topic was looking at how manipulating certain characteristics of specific cell types would help in understanding the workings of the central nervous system (CNS). He is focusing specifically on how the CNS integrates internal neuronal and endocrine signals with external sensory stimuli to generate a suitable behavioral response. Dr. Güler's lab has already been successful in discovering a neuronal link between the dopaminergic system and the central circadian clock (or circadian oscillator) that is required for circadian entrainment in mammals. For this seminar report, I will be focusing on the experiments he discussed centering around dopamine neurons and their role in the SCN with circadian rhyhtm and entrainment.
  
  *Background*: Dopamine neurons respond to salient events so that they can signal to the brain that something of importance is taking place. This forces the organism to pay attention to certain stimuli and can help direct attention towards mostly rewarding events. The elevation of dopamine neurons increases SCN neuron activity, which effectively controls the downstream daily oscillatory activity. Furthemore, Dr. Güler noted that capsaicin, a neuropeptide releasing agent that is specific for primary sensory peripheral neurons, induces a dopamine release, in the form of DAT-TRPV1 and mouses that are injected with capsaicin react similarly to like they are on cocaine. It was also measured that c-fos, which is a proto-oncogene that is used as a marker for neuronal activity post peripheral stimulation, increased because of more active neurons firing. Finally, D1 dopamine receptor (Drd1) is an important receptor that is expressed within the SCN is is vital for accurate timed re-synchronization of phase-activity rhythms. Effectively, through elevation of dopainergic tones leads to activation of VTA and thus DA neurons induces the process of photoentrainment. 

  *Experimental Design*: Güler used population of mice as samples. Experiments were conducted in controlled environments to assess the affects of RGCs, Drd1-SCN neurons and eating patterns/food consumption. The samples of mice were also in proximity to a running wheel, which they could use without constraint. It was initially found that mice generally ran on the wheel at night, which makes sense as they are nocturnal animals. They would quickly adjust to phases of light and dark cycles. When intrinsically photosensitive RGC were removed, the mice were then unable to detect light (and thus was unable to differentiate between day and night) and started free running at all times during the day. This signals that SCN also receives non-photic information regarding environmental events. 
  
  *Research Question/Hypothesis 1*: Based on the affects of Drd1-SCN neurons on the circadian rhythm, the first research question that was asked was how does the activation of Drd1-SCN neurons mimic the phase response to light? 
  *Methods 1*: The research question was answered by evaluating the mice's behavioral response to selective activation of Drd1-SCN neurons by administering a drug clozapine-N-oxide (CNO) that would selectively activate the these neurons via the Designer Receptors Exclusively Activated by Designer Drugs (DREADD) system. CNO was delivered at various times in the day to assess how the mice shifted their activity (measured by running on the wheel). Therefore, the independent variable was the time the drug was delivered to the mice and the dependent variable was the level of activity (measured with use of wheel) at various times during the day. The concentration of drug CNO remained constant. CNO was delivered at both the night time (dark phase) and during the day time (light phase), specifically 6 hours prior activity onset at circadian time, 2 hours post and 10 hours post activity onset. 
  *Conclusion 1*: It was found that when the drug CNO was delivered during the light phase (6 hours prior to activity onset), it had no significant effect on phase response. In other words, they did not shift their activity. However, when CNO was delivered during the night phase (2 and 10 hours post activity onset), the mice began shifting their activity, demonstrating a phase delay of wheel-running activity. These findings demonstrated that selective activation, with CNO, of Drd1-SCN neurons augmented the responsiveness of the circadian rhythm to photic inputs that allowed for more photoentrainment. In other words, selective activation of these neurons mirrored the effect of light during the night but failed to elicit a response during the day, which is when the circadian clock is sensitive to non-photic entrainment points. Essentially, CNO activates the Drd1 in the SCN which gives the mice some sort of "jet lag": without Drd1, the mice is much slower or unresponsiveness in shifting their cycles. 
 
  *Research Question/Hypothesis 2*: The second research question that was investigated was how does dopamine regulate rewarding food consumption?
  *Methods 2*: In this method, the independent variable was whether the mice would be reward with food foraging or not (Boolean - yes/no) and the dependent variable was measuring if the DA neurons were activated. They also measured body the correlation between rewarding food foraging and an increase in body weight, the latter being another dependent variable of this experiment. Therefore, for one group of mice, their food foraging was rewarded and for the other group, it was not rewarded. All other aspects remained constant to avoid confounding.
  *Conclusion 2*: Throughout this experiment, it was found that rewarding food foraging lead to DA neurons not only being activated, but also lead to an increase in body weight. The type of eating was also differentiated between hedonic overeating, which is eating for pleasure, and homeostatic dysregulation, which is eating for need but the dysregulation indicates that it is abnormal. It was discovered that homeostatic dysregulation caused an increase in food consumption, which caused hedonic overeating. This culminated in metabolic disorganization and obesity. The homeostatic food consumption is controlled by the hypothalamus. 
  
  *Research Question/Hypothesis 3*: The last research question that I will focus on from Güler's presentation was the idea of determining which dopamine pathways regulate foraging during inactive periods? 
  *Methods 3*: Concerning this research question/hypothesis, the independent variable was changing the amount of Drd1-SCN neuron signaling and the dependent variable was measuring the amount of eating as a result. Also, the goal of this experiment was to classify the type of eating (either hedonic overeating or homeostatic dysregulation) based on Drd1-SCN signaling. Güler hypothesized that Drd1-SCN signaling would lead to hedonic overeating because it was found in previous experiments that these neurons cause an increase in food consumption and weight gain and the type of eating habit that is most associated with weight gain is hedonic overeating. 
  *Conclusion 3*: After carrying out this experiment, they were able to confirm their hypothesis that increased Drd1-SCN signaling lead to hedonic overeating. It did so by inhibiting the activity of other SCN neurons and thereby rewarded food foraging. This subsequently lead to increase in food consumption (via hedonic overeating) and weight gain. 

  *Is the research relevant to your project?*: Our project involves looking at genotype-phenotype relationships for molecular trains in ALS. This seminar does not relate to our project; however it was informational to look at how formulating research questions/hypotheses and creating and carrying out methods were used to connected sub-aims to understand and answer an overarching research question. This knowledge can be helpful towards our own project.  
  
  *Question 1 addressed towards speaker*: Regarding research question/hypothesis 1, I would like to know specifically how the drug CNO selectively activates the Drd1-SCN neurons? Also, does CNO have an affect on food consumption and weight gain? If so, what is this connection? Would it similarly stimulate Drd1-SCN neurons to promote food consumption and therefore lead to weight gain? Furthemore, what type of food consumption would be induce: homeostatic dysregulation or hedonic overeating?
  *Question 2 addressed towards speaker*: Regarding research question/hypothesis 3, I would like to know specifically which SCN neurons did increased Drd1-SCN signaling inhibit for food foraging to be rewarded and the mice to increase food consumption via hedonic overeating? 
  
  *Take-home*: The take home conclusions from this seminar was that circadian rhythms and DA neurotransmitters are important for several behaviors. Overall it was found that specific drugs can selectively activate Drd1-SCN neurons which would increase responsiveness of the circadian rhythms and therefore increase photoentrainment. Similarly, if the mice were rewarded for food foraging, ti caused DA neurons to be activated, leading to increased Drd1-SCN signaling, and increased hedonic overeating. This therefore caused increased food consumption and weight gain. Overall, this highlights the significant effect of DA on the internal circadian clock and the relationship between the circadian system (light and dark phases) and the CNS neuronal circuits. 

  *Closing Statement*: I very much enjoyed this seminar as I thought it was very interesting and Dr. Güler delineated his hypotheses and experiments of his lab relatively clearly. I do think that the seminar could have been improved if Güler provided slightly more detail on their methods and respective conclusions because it was a little difficult to follow those points. I also really appreciated how he didn't use extremely complex terminology, that would have otherwise been too convoluted for those who are not very knowledge on the subject. Finally, I think Dr. Güler spoke at good pace that was easy to understand and follow. 
